---
- name: Install nginx
  ansible.builtin.apt:
    name: nginx
    state: present

- name: Set nginx configuration
  ansible.builtin.template:
    src: nginx.conf.j2
    dest: /etc/nginx/sites-available/default
    mode: '0644'
  notify: Restart nginx

- name: Open port 80 using UFW
  community.general.ufw:
    rule: allow
    port: 80
    proto: tcp
