---
- name: Debug facts
  ansible.builtin.debug:
    msg: "Distribution release: {{ ansible_distribution_release }}. Arch: {{ ansible_architecture }}"
  tags:
    - debug

- name: Instal necessary packages
  ansible.builtin.apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common
    state: present

- name: Download docker repo GPG-key
  ansible.builtin.apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    keyring: "{{ docker_repo_key_path }}"
    state: present

- name: Add docker repository
  vars:
    repo_options: "[arch={{ ansible_architecture }} signed-by={{ docker_repo_key_path }}]"
  ansible.builtin.apt_repository:
    repo: "deb {{ repo_options }} https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
    update_cache: true


- name: Install docker-ce
  ansible.builtin.apt:
    name: docker-ce
    state: present

- name: Start docker service
  ansible.builtin.service:
    name: docker
    state: started
    enabled: true

- name: Login in private docker hub registry
  community.docker.docker_login:
    registry: https://index.docker.io/v1/
    username: "{{ docker_user }}"
    password: "{{ docker_pass }}"

- name: Run docker containers
  loop: "{{ range(1, docker_container_count + 1) | list }}"
  vars:
    current_container_name: "{{ docker_container_name }}-{{ item }}"
    host_port: "800{{ item }}"
  community.docker.docker_container:
    name: "{{ current_container_name }}"
    image: "{{ docker_image_name }}"
    ports:
      - "{{ host_port }}:8000"
    restart_policy: always
